# Generated by Django 3.1.4 on 2021-01-02 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=20, unique=True)),
                ('bookauthor', models.CharField(default='空', max_length=10)),
                ('bookprice', models.FloatField(default=20.0)),
                ('bookpublic', models.CharField(max_length=20)),
                ('bookaddtime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Book',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('di', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.IntegerField(unique=True)),
                ('email', models.CharField(max_length=20, null=True, unique=True)),
                ('age', models.IntegerField(null=True)),
                ('sex', models.CharField(max_length=2, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('allowed', models.IntegerField(choices=[(1, '允许登录'), (2, '禁⽌登录')], default=1)),
                ('name', models.CharField(default='空', max_length=20)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Bookfigure',
            fields=[
                ('di', models.AutoField(primary_key=True, serialize=False)),
                ('book', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='APP1.book')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='APP1.user')),
            ],
            options={
                'db_table': 'Bookfigure',
            },
        ),
    ]
